theme: minima
title: Timothy R. McDade
tagline: A Political Economist.
author: Timothy R. McDade
email: tim.mcdade@duke.edu

show_excerpts: false

# social_links:
twitter_username: trmcdade
github_username: trmcdade
linkedin_username: timothymcdade

header_pages:
  - education.md
  - professionalexperience.md
  - publications.md
  - skills.md
  - cv.md

# layout: default

sass:
  sass_dir: assets/css/_sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sass-converter

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
