theme: jekyll-theme-leap-day
title: Welcome to Tim's homepage!
author: 
  name: Timothy R. McDade
  email: tim.mcdade@duke.edu
description: Feel free to bookmark this site to kepe an eye on my updates.

show_excerpts: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

social_links: 
  twitter: trmcdade
  github: trmcdade
  linkedin: timothymcdade
