theme: minima
title: Timothy R. McDade
author: Timothy R. McDade
email: tim.mcdade@duke.edu

show_excerpts: false

# social_links: 
twitter_username: trmcdade
github_username: trmcdade
linkedin_username: timothymcdade

header_pages: 
  - education.md
  - interests.md
  - professionalexperience.md
  - publications.md
  - skills.md

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
